#!/usr/bin/env php
<?php

$autoloaderIncluded = false;
foreach ([__DIR__ .'/../../autoload.php', __DIR__ .'/vendor/autoload.php'] as $autoloader) {
    if(file_exists($autoloader)) {
        $autoloaderIncluded = true;
        require_once $autoloader;
    }
}

if(!$autoloaderIncluded) {
    echo "psalm-fmt: could't find composer autoloader";
    exit(1);
}

require_once __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'psalm-formatter.php';